config/routes.rb
Rails.application.routes.draw do
  

  get 'home/index'

  devise_for :users
  

  get 'welcome/index'

  resources :spoils do
    member do
      patch :complete
    end
  end

  resources :lists do
    resources :list_items do
      member do
        patch :complete
      end
    end
  end

  authenticated :user do
    root "home#index", as: "authenticated_root"
  end

  root 'welcome#index'

end

app/models/list.rb
class List < ActiveRecord::Base
  belongs_to :user
  has_many :list_items, dependent: :delete_all
end

app/models/list_item.rb
 class ListItem < ActiveRecord::Base
  belongs_to :list

   def completed?
     !completed_at.blank?
   end

end

app/models/spoil.rb
class Spoil < ActiveRecord::Base
  belongs_to :user

  def completed?
    !completed_at.blank?
  end
  
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :lists
  has_many :spoils
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @lists = List.where(user_id: current_user)
    @list_items = ListItem.order(due_date: :ASC)
   end
  
end

app/controllers/list_items_controller.rb
 class ListItemsController < ApplicationController
  before_action :set_list
  before_action :set_list_item, except: [:create]

  def create
    @list_item = @list.list_items.create(list_item_params)
    redirect_to @list
  end

  def destroy
    @list_item.destroy
    redirect_to @list
  end

  def complete
    @list_item.update_attribute(:completed_at, Time.now)
    @list_item.update_attribute(:point_value, 1)
    @user_points = current_user.points + 1
    current_user.update_attribute(:points, @user_points )
    redirect_to @list
  end

  # def due_date
  #   @due_date = @list_item.due_date
  # end

  # def complete
  #   @list_item.toggle_completion!
  #   redirect_to @list
  # end

  private

  def set_list
    @list = List.find(params[:list_id])
  end

  def set_list_item
    @list_item = @list.list_items.find(params[:id])
  end

  def list_item_params
    params[:list_item].permit(:content, :color, :point_value, :list_id, :due_date)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :find_list, only: [:show, :edit, :update, :destroy]

  def index
    @lists = List.where(user_id: current_user)
  end

  def show
  end

  def new
    @list = current_user.lists.build
  end

  def edit
  end

  def create
    @list = current_user.lists.build(list_params)

    if @list.save
      redirect_to @list
    else
      render 'new'
    end
  end

  def update
    respond_to do |format|
      if @list.update(list_params)
        format.html { redirect_to @list }
        format.json { render :show, status: :ok, location: @list }
      else
        format.html { render :edit }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @list.destroy
    respond_to do |format|
      format.html { redirect_to home_index_path }
      format.json { head :no_content }
    end
  end

  private

  def find_list
    @list = List.find(params[:id])
    @theme = @list.color
  end

  def list_params
    params.require(:list).permit(:color, :title)
  end
end

app/controllers/spoils_controller.rb
class SpoilsController < ApplicationController
  # before_action :set_spoil

  def index
    @spoils = Spoil.where(user_id: current_user)
  end

  def show
    @spoil = Spoil.find(params[:id])
  end

  def new
    @spoil = current_user.spoils.build
  end

  def edit
  end

  def complete
    @spoil = Spoil.find(params[:id])
    @user_points = current_user.points
    @spoil_value = @spoil.point_value
    if @user_points >= @spoil_value
      @spoil.update_attribute(:completed_at, Time.now)
      @user_points = current_user.points - @spoil_value
      current_user.update_attribute(:points, @user_points )
      redirect_to spoils_path
      @spoil.destroy
    else
      redirect_to spoil_path, notice: "You don't have enough points for this :("
    end
  end

  def create
    @spoil = current_user.spoils.build(spoil_params)

    if @spoil.save
      redirect_to spoils_path
    else
      render 'new'
    end
  end

  def update
  end

  def destroy
    @spoil = Spoil.find(params[:id])    
    @spoil.destroy
    respond_to do |format|
      format.html { redirect_to spoils_path }
      format.json { head :no_content }
    end
  end

  private

  def set_spoil
    @spoil = Spoil.find(params[:id])
  end

  def spoil_params
    params.require(:spoil).permit(:content, :point_value, :user_id)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
   def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/list_items_helper.rb
module ListItemsHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/spoils_helper.rb
module SpoilsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/home/_list_items.html.haml
- @list_items.each do |list_item|
  .row
    %div{class: "item #{@list_theme}"}
      .complete
        = link_to complete_list_list_item_path(@lists, list_item.id), method: :patch do
          %i.fa.fa-circle-o
      .trash
        = link_to list_list_item_path(@lists, list_item.id), method: :delete, data: { confirm: "Delete?" } do
          %i.fa.fa-trash-o
      .list-item
        / - if list_item.toggle_completion!
        -if list_item.completed?
          %strike{ style: "opacity: 0.4;" }= list_item.content
          %br/
          .time
            Completed
            = time_ago_in_words(list_item.completed_at)
            ago
        - else
          = list_item.content
          %br/
          .time
            Created
            = time_ago_in_words(list_item.created_at)
            ago

app/views/home/_lists.html.haml
- @lists.each do |list|
  = link_to list do
    .row
      %div{class: "list #{list.color}"}
        .item-count
          = list.list_items.count
          / = link_to 'Delete', list, method: :delete, data: { confirm: "Are you sure?" }
        .list-name
          = list.title

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Spoilist</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href='https://fonts.googleapis.com/css?family=Roboto:400,300,700' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Raleway:400,600' rel='stylesheet' type='text/css'>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
</head>
<body>

  <div class="wrapper">
    <%= yield %>
  </div>

</body>
</html>

app/views/list_items/_form.html.haml
= simple_form_for([@list, @list.list_items.build]) do |f|
  = f.text_field :content, placeholder: "Add item"
  %br/
  %br/
  = f.text_field :due_date, placeholder: "Enter a date"
  %br/
  %br/
  = f.submit

app/views/list_items/_list_item.html.haml
.row
  -if list_item.completed?
    %div{class: "item #{@theme}"}
      .complete
        %i.fa.fa-check
      .trash
        = link_to list_list_item_path(@list, list_item.id), method: :delete, data: { confirm: "Delete?" } do
          %i.fa.fa-trash-o
      .list-item
        %strike{ style: "opacity: 0.4;" }= list_item.content
        %br/
        .time
          Completed
          = time_ago_in_words(list_item.completed_at)
          ago
  - else
    %div{class: "item #{@theme}"}
      .complete
        = link_to complete_list_list_item_path(@list, list_item.id), method: :patch do
          %i.fa.fa-circle-o
      .trash
        = link_to list_list_item_path(@list, list_item.id), method: :delete, data: { confirm: "Delete?" } do
          %i.fa.fa-trash-o
      .list-item
        = list_item.content
        %br/
        .time
          Created
          = time_ago_in_words(list_item.created_at)
          ago
      

app/views/list_items/complete.html.erb
<h1>ListItems#complete</h1>
<p>Find me in app/views/list_items/complete.html.erb</p>

app/views/list_items/create.html.erb
<h1>ListItems#create</h1>
<p>Find me in app/views/list_items/create.html.erb</p>

app/views/list_items/destroy.html.erb
<h1>ListItems#destroy</h1>
<p>Find me in app/views/list_items/destroy.html.erb</p>

app/views/lists/_form.html.haml
= simple_form_for @list do |f|
  = f.text_field :title, placeholder: " Title"
  %br/
  %br/
  %h3 Pick a color
  .color-theme
    .yellow-radio
      = f.radio_button :color, :yellow
    .blue-radio
      = f.radio_button :color, :blue
    .green-radio
      = f.radio_button :color, :green
    .purple-radio
      = f.radio_button :color, :purple
    .salmon-radio
      = f.radio_button :color, :salmon
  %br/
  %br/
  = f.button :submit, "Create list" 

app/views/lists/create.html.erb
<h1>Lists#create</h1>
<p>Find me in app/views/lists/create.html.erb</p>

app/views/lists/create.html.haml
<h1>Lists#create</h1>
<p>Find me in app/views/lists/create.html.erb</p>

app/views/lists/destroy.html.erb
<h1>Lists#destroy</h1>
<p>Find me in app/views/lists/destroy.html.erb</p>

app/views/lists/edit.html.haml
%h1 Edit list

= render 'form'

= link_to 'Cancel', lists_path

app/views/lists/index.html.haml
- @lists.each do |list|
  = link_to list do
    .row
      .list
        .item-count
          = list.list_items.count
          / = link_to 'Delete', list, method: :delete, data: { confirm: "Are you sure?" }
        .list-name
          = list.title
%br/
= link_to "New List", new_list_path

app/views/lists/new.html.haml
.main-row
  .back
    = link_to home_index_path do
      %i.fa.fa-angle-left
  %h1 New list
  = render 'form'

app/views/lists/show.html.haml
.row
  %div{class: "title #{@theme}"}
    .back
      = link_to home_index_path do
        %i.fa.fa-angle-left
    .trash
      = link_to @list, method: :delete, data: { confirm: "Delete?" } do
        %i.fa.fa-trash-o
    .list-name
      = @list.title
      / = link_to "Edit", edit_list_path(@list)

= render @list.list_items

= render 'list_items/form'

app/views/lists/update.html.erb
<h1>Lists#update</h1>
<p>Find me in app/views/lists/update.html.erb</p>

app/views/spoils/_form.html.haml
= simple_form_for @spoil do |f|
  = f.text_field :content, placeholder: " Title"
  %br/
  %br/
  = f.input :point_value, label: false, placeholder: 'Enter points'
  %br/
  = f.button :submit, "Create spoil" 

app/views/spoils/create.html.erb
<h1>Spoils#create</h1>
<p>Find me in app/views/spoils/create.html.erb</p>

app/views/spoils/destroy.html.erb
<h1>Spoils#destroy</h1>
<p>Find me in app/views/spoils/destroy.html.erb</p>

app/views/spoils/edit.html.erb
<h1>Spoils#edit</h1>
<p>Find me in app/views/spoils/edit.html.erb</p>

app/views/spoils/index.html.erb
<div class="row">
  <div class="back">
    <%= link_to home_index_path do %>
      <i class="fa fa-angle-left"></i>
    <% end %>
  </div>
  <h1>Spoils</h1>
</div>

<% @spoils.each do |spoil| %>
  <%= link_to spoil do %>
    <div class="row">
      <div class="title">
        <div class="spoil-points">
          <%= spoil.point_value %>
        </div>
        <div class="spoil-trash">Points needed: </div>
        <div class="spoil-name">
          <%= spoil.content %>
        </div>
      </div>    
    </div>
  <% end %>
<% end %>

app/views/spoils/new.html.erb
<!-- .main-row
  .back
    = link_to home_index_path do
      %i.fa.fa-angle-left
  %h1 New list
  = render 'form' -->

<div class="main-row">
  <div class="back">
    <%= link_to home_index_path do %>
      <i class="fa fa-angle-left"></i>
    <% end %>
  </div>
  <h1>New spoil</h1>
  <%= render 'form' %>
</div>

app/views/spoils/show.html.erb
<div class="row">
  <div class="title">
    <div class="back">
      <%= link_to spoils_path do %>
        <i class="fa fa-angle-left"></i>
      <% end %>
    </div>
    <div class="trash">
      <%= link_to spoil_path(@spoil), method: :delete, data: { confirm: "Delete?" } do %>
        <i class="fa fa-trash-o"></i>
      <% end %>
    </div>
    <div class="spoil-points">
      <%= @spoil.point_value %>
    </div>
    <div class="spoil-trash">Points needed: </div>
    <div class="list-name">
      <%= @spoil.content %>
    </div>
  </div>
</div>
<%= link_to complete_spoil_path(@spoil), method: :patch do %>
  <button class="full">
    Get your Spoil!
  </button>
<% end %>
<br>
<br>
<h2><%= notice %></h2>

app/views/spoils/update.html.erb
<h1>Spoils#update</h1>
<p>Find me in app/views/spoils/update.html.erb</p>

app/views/welcome/_form.html.haml
.wrapper

  = simple_form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f|
    = f.error_notification

    .form-inputs
      = f.text_field :username, required: true, placeholder: " Username"
      %br/
      %br/
      = f.email_field :email, required: true, placeholder: " Email"
      %br/
      %br/
      = f.password_field :password, required: true, hint: ("#{@minimum_password_length} characters minimum" if @minimum_password_length), placeholder: " Password"
      %br/
      %br/
      = f.password_field :password_confirmation, required: true, placeholder: " Password Confirmation"
    %br/
    .form-actions
      = f.button :submit, "Sign up"

app/views/welcome/index.html.haml
.welcome
  = link_to new_user_session_path do
    %button.c-button
      Log in
  .logo
    = link_to image_tag( 'logo.svg'), root_path, id: "logo"
  %h1 Spoilist
  %p Spoil yourself while organizing your busy life! Spoilist helps you manage your hectic schedule and rewards you for getting stuff done.
  %br/
  %h2 Sign up
= render 'form'

.footer
  &copy; MATT CARRINGTON